version: "3"
services: 
    webhook:
      build: 
        context: ./webhook
        dockerfile: ./Dockerfile
      ports:
      - "3000:3000"
    vigil:
      image: dalongrong/vigil:v1.12.1
      command: vigil -c /opt/config.cfg
      volumes: 
      - "./config.cfg:/opt/config.cfg"
      ports:
      - "8080:8080"